.TH BLOCKLIST.CONF 5 BLOCKLIST.CONF\-1.0
.SH NAME
blocklist.conf \- configuration file for \fBproject\fR(1)
.SH DESCRIPTION
Block domains for certain time frames.
.SH SECTION: DAYS
.TP
.I n
.br
.RS 4
Days (i.e. 1 for monday, 7 for sunday). Setting "all" will block all day long, you can also give a range (i.e. 1400-1800 for "block from 2pm to 6pm").
.SH SECTION: DOMAINS
.TP
.I domain
.br
.RS 4
Domain names you want blocked. If the website is "www.youtube.com" don't forget the "www.". Write domains line per line.
.SH SEE ALSO
.BR project (8)
